import {
  AddAddress,
  Address,
  Cart,
  Checkout,
  DetailSupportTicket,
  EditAddress,
  Order,
  OrderDetail,
  Payment,
  PaymentMethod,
  PaymentMethodAdd,
  PaymentMethodEdit,
  Profile,
  ProfileEdit,
  SupportTicket,
  WishList,
} from 'src/routes/elements';

export default [
  { path: '/cart', component: Cart, index: true },
  { path: '/checkout', component: Checkout, index: true },
  { path: '/payment', component: Payment, index: true },
  { path: '/order', component: Order, index: true },
  { path: '/order/:id', component: OrderDetail, index: true },
  { path: '/profile', component: Profile, index: true },
  { path: '/profile/:id', component: ProfileEdit, index: true },
  { path: '/address', component: Address, index: true },
  { path: '/address/add', component: AddAddress, index: true },
  { path: '/address/:id', component: EditAddress, index: true },
  { path: '/payment-methods', component: PaymentMethod, index: true },
  { path: '/payment-method/:id', component: PaymentMethodEdit, index: true },
  { path: '/payment-method/add', component: PaymentMethodAdd, index: true },
  { path: '/support-tickets', component: SupportTicket, index: true },
  { path: '/support-ticket/:id', component: DetailSupportTicket, index: true },
  { path: '/wish-list', component: WishList, index: true },
];
